#注册中心集群
server: 
  port: 8761
spring: 
  profiles: peer1
eureka: 
  instance: 
    hostname: peer1
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  server: 
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false 
    service-url: 
      defaultZone: http://peer2:8769/eureka/
