server:
  port: 888
spring:
  profiles : dev
  application:
    name: springCloud_mybatis     #应用名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.74.154.133:3306/testDb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: Hunge//..22@
    name: mydb  
    type: com.alibaba.druid.pool.DruidDataSource  
    minIdle: 1  
    maxActive: 2  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 'ZTM' FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false
mybatis:   
  mapperLocations: classpath*:com/homefun/mapper/*.xml  
  typeAliasesPackage: com.homefun.beans