spring: 
    datasource:
      url: jdbc:mysql://47.74.154.133:3306/testDb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: Hunge//..22@
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    thymeleaf: 
       cache: false
       mode: LEGACYHTML5