#=============================redis 配置=============================
spring: 
  redis:
    cluster:                     # cluster 集群配置
      max-redirects: 3           # 尝试3次最多
      nodes:
      - 192.168.1.9:6380  
      - 192.168.1.8:6379
    database: 0                 # Redis数据库索引（默认为0）
    host: 192.168.1.8           # Redis服务器地址
    port: 6379                  # Redis服务器连接端口
    password:                   # Redis服务器连接密码（默认为空）
    pool:
      max-active: -1            # 连接池最大连接数（使用负值表示没有限制）如果赋值为-1，则表示不限制
      max-wait: -1              # 连接池最大阻塞等待时间（使用负值表示没有限制）默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException；
      max-idle: 60              # 连接池中的最大空闲连接
      min-idle: 10              # 连接池中的最小空闲连接
    timeout: 3000               # 连接超时时间（毫秒）