spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      #改造成微服务, 不直接向配置中心取，配置中心作为eureka服务的一个提供者而变成集群，从而向服务注册中心获取
      #uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
  # 消息总线配置
  rabbitmq:
    host: localhost
    port: 5672
management:
  security:
    enabled: false    
  # rabbitmq有用户密码再设置
# spring.rabbitmq.username=
# spring.rabbitmq.password=
server:
  port: 8881
#微服务改造
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/