server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.1.7
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaulZone: http://${eureka.instance.hostname}:${server.port}/registry/